## elasticsearch image version
## ref: https://hub.docker.com/_/elasticsearch/
##
imageTag: 2.4.1

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## Resource limits
cpu: 200m
memory: 300Mi

## PVC storage size
storageSize: 25Gi

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
