## Bitnami Redis image version
## ref: https://hub.docker.com/r/bitnami/redis/tags/
##
imageTag: 3.2.4-r0

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## Redis password
## ref: https://github.com/bitnami/bitnami-docker-redis#setting-the-server-password-on-first-run
##
# redisPassword:

## Resource limits
cpu: 200m
memory: 300Mi

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
