## Bitnami Memcached image version
## ref: https://hub.docker.com/r/bitnami/mariadb/tags/
##
imageTag: 1.4.25-r6

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:
#
## Memcached admin user
## ref: https://github.com/bitnami/bitnami-docker-memcached#creating-the-memcached-admin-user
##
# memcachedUsername:

## Memcached admin password
## ref: https://github.com/bitnami/bitnami-docker-memcached#creating-the-memcached-admin-user
##
# memcachedPassword:

## Resource limits
cpu: 200m
memory: 300Mi

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
