## zipkin-collector image version
##
image: b.gcr.io/stackdriver-trace-docker/zipkin-collector

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Replicas Set count
replicasCount: 2

## GCP project ID
gcpProjectID: ""

## GCP service account key
gcpServiceAccountKey: 'Paste JSON data here.'

## Resource limits
cpu: 100m
memory: 100Mi

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
