apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-deis
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  user-token: {{ .Values.workflowUserToken | b64enc }}
