apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  credentials: |-
    {{ .Values.awsCreds | b64enc }}
