## Coreroller image version
## ref: https://hub.docker.com/r/coreroller/rollerd/
##
image: coreroller/rollerd:latest

## Specify a imagePullPolicy
## Defaults to 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Resource limits
cpu: 150m
memory: 150Mi

## PostgreSQL chart configuration
##
postgresql:
 # PVC storage size
 storageSize: 10Gi

 ## Resource limits
 cpu: 150m
 memory: 200Mi

## Node selector
## comment it out if you do not need to use node selector
## e.g. "role: worker-general"
nodeSelector:
  role: worker-general
