## Buildkite agent image version
## ref: https://hub.docker.com/r/buildkite/agent/
##
image: buildkite/agent:latest

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Agent docker image tag
dockerTag: 1.12.

## Replicas Set count
replicasCount: 11

## Agent release tag, to be used just to trigger a new release of the agent
## and pull the latest docker image, as buildkite agent has no version tags yet
agentTag: "2.3.1"

## Agent meta-data, which can be used to assign jobs
agentMeta: "role=deploy"

## Your Buildkite agent token
agentToken: "token"

## Your ssh private key
privateSshKey: "ssh_key"

## Resource limits
cpu: 100m
memory: 200Mi

## Deis Workflow PaaS
## user token - client.json content encoded with base64
workflowUserToken: " "
##
## API URL
workflowApiUrl: " "

## ANY EXTRA ENV VAR TO BE PASSED TO BUILDKITE AGENT
##
extraEnvVar:
  name: SOME_ENV_VAR
  value: "some_value"

## Node selector
## uncomment it if you do need to use node selector
## e.g. "role: worker-general"
# nodeSelector:
#   role: worker-general
