name: pgbouncer
version: 0.1.0
description: Chart for PGBouncer
keywords:
- postgresql
- database
- sql
home: https://pgbouncer.github.io
sources:
- https://github.com/clearbit/charts
maintainers:
- name: Clearbit
  email: ops+containers@clearbit.com
engine: gotpl
