apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    router.deis.io/routable: "true"
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    router.deis.io/domains: scope
    router.deis.io/connectTimeout: "10"
    router.deis.io/tcpTimeout: "1200"
spec:
  #type: LoadBalancer
  ports:
    - name: app
      port: 80
      targetPort: 4040
      protocol: TCP
  selector:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
